version: '3.8'

services:
  nuxt:
    build:
      context: .  # Context refers to the root directory, where Dockerfile should be
      dockerfile: Dockerfile  # Path to the Dockerfile
    working_dir: /app
    volumes:
      - .:/app   # Mount the current directory to /app inside the container
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Custom nginx config
      - /etc/letsencrypt/live/sheen-antel.homeagent.site:/etc/letsencrypt/live/sheen-antel.homeagent.site  # Mount Let's Encrypt certificates
      - ./dist:/usr/share/nginx/html   # Mount the `dist` folder to serve the built app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
