version: "3.7"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sheen-website_nuxt_1
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    ports:
      - "3000:3000" # Exposing Nuxt to port 3000 for Nginx to proxy
    networks:
      - sheen-website-network

  nginx:
    image: nginx:alpine
    container_name: sheen-website_nginx_1
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro # Mount AWS SSL certificates directory
      - ./dist:/usr/share/nginx/html # Serve the Nuxt production files
    ports:
      - "80:80"
      - "443:443" # Expose HTTPS port 443
    depends_on:
      - nuxt
    networks:
      - sheen-website-network

networks:
  sheen-website-network:
    driver: bridge
