version: '3.8'

services:
  nuxt:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./app:/app
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/sheen-antel.homeagent.site:/etc/letsencrypt/live/sheen-antel.homeagent.site  # Mount Let's Encrypt certificates
      - ./dist:/usr/share/nginx/html   # Mount the `dist` folder to serve the built app
    networks:
      - app-network
    # Do not use `depends_on` here because it is unnecessary for nginx to depend on nuxt in this case

networks:
  app-network:
    driver: bridge
