version: "3"
services:
  app:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./dist:/usr/share/nginx/html
    depends_on:
      - nginx
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
