version: '3.8'

services:
  nuxt:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm run dev  # Run Nuxt.js in development mode
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"  # Expose port 443 for HTTPS
    volumes:
      - .:/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl  # Mount the SSL folder into the container
    depends_on:
      - nuxt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
